#!/usr/bin/with-contenv bash
# ==============================================================================
# Node-RED for Home Assistant Core
# Configures Node-RED before running
# ==============================================================================

# Ensure configuration files exist
FILE=/app/flows.json
if [ -f "$FILE" ]; then
    echo "$FILE exists."
else
    echo "[]" >> $FILE
fi

FILE=/app/settings.js
if [ -f "$FILE" ]; then
    echo "$FILE exists."
else
    cp /etc/node-red/settings.js $FILE
fi

# Check to see if the home assistant server has already been defined
jq -e '[ .[] | select(.name=="Home Assistant")]' /app/flows.json | grep "\[\]" &> /dev/null
if [ $? == 0 ]; then
    echo "home assistant server already defined"
else
    # Create random flow id
    id=$(node -e "console.log((1+Math.random()*4294967295).toString(16));")

    # Inject HA URL and access token
    json_string=$( jq -n \
                        --arg id "${id}" \
                        --arg url "${HOMEASSISTANT_URL}" \
                        --arg token "${HOMEASSISTANT_TOKEN}" \
                        '[{"id":$id,"type":"server","z":"","name":"Home Assistant","addon":false,"url":$url,"pass":$token}]')

    jq -c \
        --arg haelement "${json_string}" \
        '. += $haelement' /app/flows.json > flows.ha
    mv flows.ha /app/flows.json
fi

# Ensures conflicting Node-RED packages are absent
cd /app
if [ -f "/app/package.json" ]; then
    npm uninstall \
        node-red-contrib-home-assistant \
        node-red-contrib-home-assistant-llat \
        node-red-contrib-home-assistant-ws
fi
