#!/usr/bin/with-contenv bash

set +u

CONFIG_PATH=/app/options.json
MOSQUITTO_CONF=/app/config/mosquitto.conf

if [ ! -f "${CONFIG_PATH}" ]; then
    cp /etc/mosquitto/options.json ${CONFIG_PATH}
fi

if [ ! -f "${MOSQUITTO_CONF}" ]; then
    cp /etc/mosquitto/mosquitto.conf ${MOSQUITTO_CONF}
fi

AUTH_SRV_PATH=/bin/auth_srv.sh

LOGINS=$(jq --raw-output ".logins | length" $CONFIG_PATH)
ANONYMOUS=$(jq --raw-output ".anonymous" $CONFIG_PATH)
KEYFILE=$(jq --raw-output ".keyfile" $CONFIG_PATH)
CERTFILE=$(jq --raw-output ".certfile" $CONFIG_PATH)
CAFILE=$(jq --raw-output --exit-status ".cafile | select (.!=null)" $CONFIG_PATH || echo "$CERTFILE")
REQUIRE_CERTIFICATE=$(jq --raw-output ".require_certificate" $CONFIG_PATH)
CUSTOMIZE_ACTIVE=$(jq --raw-output ".customize.active" $CONFIG_PATH)
DEBUG_LOGGING=$(jq --raw-output ".debug_logging" $CONFIG_PATH)

SSL_CONFIG="
listener 8883
protocol mqtt
cafile /ssl/$CAFILE
certfile /ssl/$CERTFILE
keyfile /ssl/$KEYFILE
require_certificate $REQUIRE_CERTIFICATE
listener 8884
protocol websockets
cafile /ssl/$CAFILE
certfile /ssl/$CERTFILE
keyfile /ssl/$KEYFILE
require_certificate $REQUIRE_CERTIFICATE
"

## Main ##

echo "Setup mosquitto configuration"

sed -i "s/%%ANONYMOUS%%/$ANONYMOUS/g" ${MOSQUITTO_CONF}
sed -i "s/%%AUTH_QUIET_LOGS%%/$DEBUG_LOGGING/g" ${MOSQUITTO_CONF}

# Enable SSL if exists configs
if [ -e "/ssl/$CAFILE" ] && [ -e "/ssl/$CERTFILE" ] && [ -e "/ssl/$KEYFILE" ]; then
    echo "$SSL_CONFIG" >> ${MOSQUITTO_CONF}
else
    echo "SSL not enabled - No valid certs found!"
fi

# Handle local users
if [ "$LOGINS" -gt "0" ]; then
    echo "Found local users inside config"
else
    echo "No local user available"
fi

chmod +x ${AUTH_SRV_PATH}