#!/usr/bin/with-contenv bash

function call_homeassistant() {
    local method=$1
    local path=$2
    local data="${3}"
    local token=

    token="Authorization: Bearer ${HOMEASSISTANT_TOKEN}"
    url="${HOMEASSISTANT_URL}/${path}"

    # Call API
    if [ -n "${data}" ]; then
        curl -f -s -X "${method}" -d "${data}" -H "${token}" "${url}"
    else
        curl -f -s -X "${method}" -H "${token}" "${url}"
    fi

    return $?
}

# Remove service
if call_homeassistant GET "services/mqtt" | jq --raw-output ".data.host" | grep "$(hostname)" > /dev/null; then
    if ! call_homeassistant DELETE "services/mqtt"; then
        echo "Service unregister fails!"
    fi
fi

s6-svscanctl -t /var/run/s6/services