#!/usr/bin/with-contenv bash
# ==============================================================================
# Mosquitto MQTT Broker
# Starts Mosquitto
# ==============================================================================

echo "Starting Mosquitto..."

# Start Auth Server
socat TCP-LISTEN:8080,fork,reuseaddr SYSTEM:/bin/auth_srv.sh &
WAIT_PIDS+=($!)

cd /usr/sbin
exec mosquitto -c /mosquitto/config/mosquitto.conf
