#!/usr/bin/with-contenv bash
# ==============================================================================
# Mosquitto MQTT Broker
# Starts Mosquitto
# ==============================================================================

SYSTEM_USER=/app/data/system_user.json
HOMEASSISTANT_PW=
ADDONS_PW=

function call_homeassistant() {
    local method=$1
    local path=$2
    local data="${3}"
    local token=

    token="Authorization: Bearer ${HOMEASSISTANT_TOKEN}"
    url="${HOMEASSISTANT_URL}/${path}"

    # Call API
    if [ -n "${data}" ]; then
        curl -f -s -X "${method}" -d "${data}" -H "${token}" "${url}"
    else
        curl -f -s -X "${method}" -H "${token}" "${url}"
    fi

    return $?
}

function constrain_host_config() {
    local user=$1
    local password=$2

    echo "{"
    echo "  \"host\": \"$(hostname)\","
    echo "  \"port\": 1883,"
    echo "  \"ssl\": false,"
    echo "  \"protocol\": \"3.1.1\","
    echo "  \"username\": \"${user}\","
    echo "  \"password\": \"${password}\""
    echo "}"
}

function constrain_discovery() {
    local user=$1
    local password=$2
    local config=

    config="$(constrain_host_config "${user}" "${password}")"
    echo "{"
    echo "  \"service\": \"mqtt\","
    echo "  \"config\": ${config}"
    echo "}"
}

function write_system_users() {
    (
        echo "{\"homeassistant\": {\"password\": \"$HOMEASSISTANT_PW\"}, \"addons\": {\"password\": \"$ADDONS_PW\"}}"
    ) > "${SYSTEM_USER}"
}

# Prepare System Accounts
if [ ! -e "${SYSTEM_USER}" ]; then
    HOMEASSISTANT_PW="$(pwgen 64 1)"
    ADDONS_PW="$(pwgen 64 1)"

    echo "Initialize system configuration."
    write_system_users
else
    HOMEASSISTANT_PW=$(jq --raw-output '.homeassistant.password' $SYSTEM_USER)
    ADDONS_PW=$(jq --raw-output '.addons.password' $SYSTEM_USER)
fi

# Initialize Service
if call_homeassistant GET "/api/services/mqtt" | jq --raw-output ".data.host" | grep -v "$(hostname)" > /dev/null; then
    echo "There is already an MQTT service running!"
else
    echo "Initialize Home Assistant Add-on services"
    if ! call_homeassistant POST "services/mqtt" "$(constrain_host_config addons "${ADDONS_PW}")" > /dev/null; then
        echo "Can't setup Home Assistant service mqtt"
    fi

    echo "Initialize Home Assistant discovery"
    if ! call_homeassistant POST "/api/discovery" "$(constrain_discovery homeassistant "${HOMEASSISTANT_PW}")" > /dev/null; then
        echo "Can't setup Home Assistant discovery mqtt"
    fi
fi

echo "Starting Mosquitto..."

cd /usr/sbin
exec mosquitto -c /app/config/mosquitto.conf
